/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as CheckoutCancelledRouteImport } from './routes/checkout-cancelled'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPromoCodesRouteImport } from './routes/admin.promo-codes'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelledRoute = CheckoutCancelledRouteImport.update({
  id: '/checkout-cancelled',
  path: '/checkout-cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoCodesRoute = AdminPromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout-cancelled': typeof CheckoutCancelledRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/events': typeof EventsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout-cancelled': typeof CheckoutCancelledRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/events': typeof EventsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout-cancelled': typeof CheckoutCancelledRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/events': typeof EventsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout-cancelled'
    | '/checkout-success'
    | '/events'
    | '/reset-password'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/orders'
    | '/admin/promo-codes'
    | '/admin/settings'
    | '/admin/users'
    | '/events/$slug'
    | '/admin/'
    | '/admin/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout-cancelled'
    | '/checkout-success'
    | '/events'
    | '/reset-password'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/orders'
    | '/admin/promo-codes'
    | '/admin/settings'
    | '/admin/users'
    | '/events/$slug'
    | '/admin'
    | '/admin/events/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout-cancelled'
    | '/checkout-success'
    | '/events'
    | '/reset-password'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/orders'
    | '/admin/promo-codes'
    | '/admin/settings'
    | '/admin/users'
    | '/events/$slug'
    | '/admin/'
    | '/admin/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutCancelledRoute: typeof CheckoutCancelledRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EventsRoute: typeof EventsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-cancelled': {
      id: '/checkout-cancelled'
      path: '/checkout-cancelled'
      fullPath: '/checkout-cancelled'
      preLoaderRoute: typeof CheckoutCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo-codes': {
      id: '/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AdminPromoCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsIdRoute: typeof AdminEventsIdRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsIdRoute: AdminEventsIdRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPromoCodesRoute: typeof AdminPromoCodesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPromoCodesRoute: AdminPromoCodesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutCancelledRoute: CheckoutCancelledRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EventsRoute: EventsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
